import type { Metadata } from "next";
import { SUSE } from "next/font/google";
import "./globals.css";

const suseMono = SUSE({
  variable: "--font-suse-mono",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${suseMono.variable} antialiased font-mono`}
      >
        {children}
      </body>
    </html>
  );
}
