import type { Metadata } from "next";
import { Italiana, Roboto, Nunito } from "next/font/google";
import "./globals.css";

  const italiana = Italiana({
    variable: "--font-italiana",
    subsets: ["latin"],
    weight: ["400"],
  });

  const roboto = Roboto({
    variable: "--font-roboto",
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500"],
  });

  const nunito = Nunito({
    variable: "--font-nunito",
    subsets: ["latin"],
    weight: ["200", "300", "400", "500", "600", "700", "800"],
  });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${italiana.variable} ${roboto.className} ${nunito.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
